/* ======================================================================
   ██████████████████████████████████████████████████████████████████████
   █  PRIORITY_CONFIG — EDIT THIS FILE ONLY.                              █
   █  This is the SOLE place that defines skill leveling priority order. █
   █  Visitors cannot edit this through the UI — only by changing this   █
   █  file and redeploying (e.g. commit + push to GitHub).               █
   █                                                                     █
   █  Format per class:                                                 █
   █  {                                                                 █
   █    nodes: [ {key, name(optional), type, level(starting)}, ... ],   █
   █    priorities: {                                                  █
   █      "Preset Name": [ ["NodeKey", targetLevel], ["NOTE","text"] ] █
   █    }                                                               █
   █  }                                                                 █
   ██████████████████████████████████████████████████████████████████████
====================================================================== */
const PRIORITY_CONFIG = {
  Hoyoung: {
    nodes: [
      {
        key: "taotie",
        name: "Sage: Liberated Taotie",
        type: "skill12",
        level: 0,
      },
      {
        key: "heavenly world",
        name: "Heavenly World",
        type: "skill12",
        level: 0,
      },
      {
        key: "apotheosis",
        name: "Sage: Apotheosis",
        type: "skill12",
        level: 1,
      },
      {
        key: "ascent",
        name: "Sage: Millennial Spirit",
        type: "skill12",
        level: 0,
      },
      {
        key: "rampage",
        name: "Sage: Maximum Clone Rampage",
        type: "enhancement",
        level: 0,
      },
      {
        key: "tiger",
        name: "Scroll: Tiger of Songyu",
        type: "enhancement",
        level: 0,
      },
      {
        key: "wrath of gods",
        name: "Sage: Wrath of Gods",
        type: "enhancement",
        level: 0,
      },
      {
        key: "apparition",
        name: "Sage: Three Paths Apparition",
        type: "enhancement",
        level: 0,
      },
      {
        key: "scroll",
        name: "Scroll: Vortex & Butterfly",
        type: "mastery",
        level: 0,
      },
      {
        key: "talisman",
        name: "Talisman: Clone & Ghost",
        type: "mastery",
        level: 0,
      },
      { key: "basics", name: "Basics Mastery", type: "mastery", level: 0 },
      { key: "harmony", name: "Universal Harmony", type: "mastery", level: 0 },
      { key: "lotus", name: "Sol Janus", type: "common12", level: 0 },
      { key: "hecate", name: "Sol Hecate", type: "common12", level: 0 },
      { key: "lotus flower", name: "Lotus Flower", type: "common3", level: 0 },
    ],
    priorities: {
      All: [
        ["harmony", 1],
        ["talisman", 1],
        ["scroll", 1],
        ["hecate", 1],
        ["harmony", 2],
        ["harmony", 3],
        ["harmony", 4],
        ["harmony", 5],
        ["harmony", 6],
        ["scroll", 2],
        ["talisman", 2],
        ["scroll", 3],
        ["NOTE", "HEXA Stat I: level to 20"],
        ["scroll", 4],
        ["talisman", 3],
        ["talisman", 4],
        ["scroll", 5],
        ["scroll", 6],
        ["talisman", 5],
        ["scroll", 7],
        ["NOTE", "HEXA Stat II: level to 20"],
        ["talisman", 6],
        ["basics", 1],
        ["basics", 2],
        ["basics", 3],
        ["basics", 4],
        ["basics", 5],
        ["basics", 6],
        ["scroll", 8],
        ["harmony", 7],
        ["harmony", 8],
        ["harmony", 9],
        ["harmony", 10],
        ["harmony", 11],
        ["harmony", 12],
        ["talisman", 7],
        ["scroll", 9],
        ["basics", 7],
        ["talisman", 8],
        ["NOTE", "HEXA Stat III: level to 20"],
        ["basics", 8],
        ["wrath of gods", 1],
        ["talisman", 9],
        ["basics", 9],
        ["apparition", 1],
        ["rampage", 1],
        ["rampage", 2],
        ["rampage", 3],
        ["rampage", 4],
        ["rampage", 5],
        ["rampage", 6],
        ["harmony", 13],
        ["harmony", 14],
        ["harmony", 15],
        ["harmony", 16],
        ["harmony", 17],
        ["harmony", 18],
        ["rampage", 7],
        ["rampage", 8],
        ["lotus", 1],
        ["ascent", 1],
        ["rampage", 9],
        ["tiger", 1],
        ["scroll", 10],
        ["scroll", 11],
        ["scroll", 12],
        ["scroll", 13],
        ["scroll", 14],
        ["scroll", 15],
        ["lotus", 2],
        ["hecate", 2],
        ["scroll", 16],
        ["talisman", 10],
        ["talisman", 11],
        ["talisman", 12],
        ["talisman", 13],
        ["talisman", 14],
        ["apotheosis", 2],
        ["harmony", 19],
        ["harmony", 20],
        ["harmony", 21],
        ["harmony", 22],
        ["harmony", 23],
        ["harmony", 24],
        ["talisman", 15],
        ["basics", 10],
        ["basics", 11],
        ["basics", 12],
        ["basics", 13],
        ["basics", 14],
        ["scroll", 17],
        ["hecate", 3],
        ["basics", 15],
        ["lotus", 3],
        ["talisman", 16],
        ["scroll", 18],
        ["basics", 16],
        ["apotheosis", 3],
        ["talisman", 17],
        ["scroll", 19],
        ["hecate", 4],
        ["basics", 17],
        ["lotus", 4],
        ["talisman", 18],
        ["harmony", 25],
        ["harmony", 26],
        ["harmony", 27],
        ["harmony", 28],
        ["harmony", 29],
        ["harmony", 30],
        ["basics", 18],
        ["apotheosis", 4],
        ["ascent", 2],
        ["talisman", 19],
        ["hecate", 5],
        ["rampage", 10],
        ["rampage", 11],
        ["rampage", 12],
        ["rampage", 13],
        ["rampage", 14],
        ["basics", 19],
        ["lotus", 5],
        ["rampage", 15],
        ["apotheosis", 5],
        ["hecate", 6],
        ["ascent", 3],
        ["rampage", 16],
        ["lotus", 6],
        ["scroll", 20],
        ["scroll", 21],
        ["scroll", 22],
        ["scroll", 23],
        ["scroll", 24],
        ["scroll", 25],
        ["scroll", 26],
        ["hecate", 7],
        ["apotheosis", 6],
        ["rampage", 17],
        ["scroll", 27],
        ["lotus", 7],
        ["ascent", 4],
        ["hecate", 8],
        ["rampage", 18],
        ["scroll", 28],
        ["scroll", 29],
        ["wrath of gods", 2],
        ["talisman", 20],
        ["talisman", 21],
        ["talisman", 22],
        ["talisman", 23],
        ["talisman", 24],
        ["talisman", 25],
        ["apotheosis", 7],
        ["talisman", 26],
        ["basics", 20],
        ["basics", 21],
        ["basics", 22],
        ["basics", 23],
        ["basics", 24],
        ["basics", 25],
        ["rampage", 19],
        ["talisman", 27],
        ["basics", 26],
        ["lotus", 8],
        ["hecate", 9],
        ["apparition", 2],
        ["apotheosis", 8],
        ["ascent", 5],
        ["basics", 27],
        ["talisman", 28],
        ["talisman", 29],
        ["wrath of gods", 3],
        ["lotus", 9],
        ["apotheosis", 9],
        ["basics", 28],
        ["basics", 29],
        ["ascent", 6],
        ["apparition", 3],
        ["wrath of gods", 4],
        ["ascent", 7],
        ["wrath of gods", 5],
        ["wrath of gods", 6],
        ["wrath of gods", 7],
        ["wrath of gods", 8],
        ["wrath of gods", 9],
        ["wrath of gods", 10],
        ["apparition", 4],
        ["rampage", 20],
        ["rampage", 21],
        ["rampage", 22],
        ["rampage", 23],
        ["rampage", 24],
        ["rampage", 25],
        ["rampage", 26],
        ["ascent", 8],
        ["rampage", 27],
        ["apparition", 5],
        ["apparition", 6],
        ["apparition", 7],
        ["apparition", 8],
        ["apparition", 9],
        ["apparition", 10],
        ["tiger", 2],
        ["rampage", 28],
        ["ascent", 9],
        ["rampage", 29],
        ["tiger", 3],
        ["apotheosis", 10],
        ["apotheosis", 11],
        ["apotheosis", 12],
        ["apotheosis", 13],
        ["hecate", 10],
        ["hecate", 11],
        ["hecate", 12],
        ["hecate", 13],
        ["hecate", 14],
        ["hecate", 15],
        ["apotheosis", 14],
        ["scroll", 30],
        ["lotus", 10],
        ["lotus", 11],
        ["lotus", 12],
        ["lotus", 13],
        ["lotus", 14],
        ["tiger", 4],
        ["lotus", 15],
        ["apotheosis", 15],
        ["tiger", 5],
        ["tiger", 6],
        ["tiger", 7],
        ["tiger", 8],
        ["tiger", 9],
        ["tiger", 10],
        ["lotus", 16],
        ["hecate", 16],
        ["talisman", 30],
        ["apotheosis", 16],
        ["lotus", 17],
        ["basics", 30],
        ["hecate", 17],
        ["apotheosis", 17],
        ["lotus", 18],
        ["wrath of gods", 11],
        ["ascent", 10],
        ["ascent", 11],
        ["ascent", 12],
        ["ascent", 13],
        ["ascent", 14],
        ["hecate", 18],
        ["apotheosis", 18],
        ["lotus", 19],
        ["hecate", 19],
        ["hecate", 20],
        ["hecate", 21],
        ["hecate", 22],
        ["hecate", 23],
        ["hecate", 24],
        ["hecate", 25],
        ["hecate", 26],
        ["hecate", 27],
        ["hecate", 28],
        ["hecate", 29],
        ["hecate", 30],
        ["apparition", 11],
        ["apotheosis", 19],
        ["apotheosis", 20],
        ["ascent", 15],
        ["wrath of gods", 12],
        ["apotheosis", 21],
        ["ascent", 16],
        ["wrath of gods", 13],
        ["wrath of gods", 14],
        ["wrath of gods", 15],
        ["wrath of gods", 16],
        ["wrath of gods", 17],
        ["wrath of gods", 18],
        ["wrath of gods", 19],
        ["wrath of gods", 20],
        ["apotheosis", 22],
        ["apparition", 12],
        ["rampage", 30],
        ["apotheosis", 23],
        ["apotheosis", 24],
        ["apotheosis", 25],
        ["apotheosis", 26],
        ["apotheosis", 27],
        ["apotheosis", 28],
        ["apotheosis", 29],
        ["apotheosis", 30],
        ["ascent", 17],
        ["apparition", 13],
        ["apparition", 14],
        ["apparition", 15],
        ["apparition", 16],
        ["apparition", 17],
        ["apparition", 18],
        ["apparition", 19],
        ["apparition", 20],
        ["ascent", 18],
        ["lotus", 20],
        ["lotus", 21],
        ["lotus", 22],
        ["lotus", 23],
        ["lotus", 24],
        ["lotus", 25],
        ["ascent", 19],
        ["lotus", 26],
        ["wrath of gods", 21],
        ["wrath of gods", 22],
        ["wrath of gods", 23],
        ["wrath of gods", 24],
        ["wrath of gods", 25],
        ["wrath of gods", 26],
        ["wrath of gods", 27],
        ["wrath of gods", 28],
        ["wrath of gods", 29],
        ["wrath of gods", 30],
        ["lotus", 27],
        ["tiger", 11],
        ["apparition", 21],
        ["apparition", 22],
        ["apparition", 23],
        ["apparition", 24],
        ["apparition", 25],
        ["apparition", 26],
        ["apparition", 27],
        ["apparition", 28],
        ["apparition", 29],
        ["apparition", 30],
        ["lotus", 28],
        ["lotus", 29],
        ["tiger", 12],
        ["ascent", 20],
        ["ascent", 21],
        ["ascent", 22],
        ["ascent", 23],
        ["ascent", 24],
        ["ascent", 25],
        ["tiger", 13],
        ["tiger", 14],
        ["tiger", 15],
        ["tiger", 16],
        ["tiger", 17],
        ["tiger", 18],
        ["tiger", 19],
        ["tiger", 20],
        ["ascent", 26],
        ["ascent", 27],
        ["ascent", 28],
        ["ascent", 29],
        ["tiger", 21],
        ["tiger", 22],
        ["tiger", 23],
        ["tiger", 24],
        ["tiger", 25],
        ["tiger", 26],
        ["tiger", 27],
        ["tiger", 28],
        ["tiger", 29],
        ["tiger", 30],
        ["ascent", 30],
        ["lotus", 30],
      ],
    },
  },

  Adele: {
    nodes: [
      { key: "Maestro", type: "skill12", level: 1 },
      { key: "Cleave", type: "mastery", level: 0 },
      { key: "Infinity", type: "enhancement", level: 0 },
      { key: "Ruin", type: "enhancement", level: 0 },
      { key: "Legacy", type: "enhancement", level: 0 },
      { key: "Storm", type: "enhancement", level: 0 },
    ],
    priorities: {
      General: [
        ["Cleave", 1],
        ["Cleave", 2],
        ["Infinity", 1],
        ["Cleave", 3],
        ["Cleave", 4],
        ["NOTE", "HEXA Stat: Main 0→2 (5 SE / 10 Frag unlock, 10 Frag/roll)"],
        ["Cleave", 5],
        ["Cleave", 6],
        ["Cleave", 7],
        ["Cleave", 8],
        ["Cleave", 9],
        ["Maestro", 2],
        ["Legacy", 1],
        ["Storm", 1],
        ["Maestro", 3],
        ["Legacy", 2],
        ["Legacy", 3],
        ["Legacy", 4],
        [
          "NOTE",
          "HEXA Stat: continue until maxed (see HEXA Stats tab for cost)",
        ],
        ["Maestro", 4],
        ["Maestro", 5],
        ["Infinity", 2],
        ["Maestro", 6],
        ["Cleave", 10],
        ["Cleave", 11],
        ["Cleave", 12],
        ["Cleave", 13],
        ["Cleave", 14],
        ["Cleave", 15],
        ["Legacy", 5],
        ["Legacy", 6],
        ["Legacy", 7],
        ["Maestro", 7],
        ["Ruin", 1],
        ["Infinity", 3],
        ["Cleave", 16],
        ["Maestro", 8],
        ["Cleave", 17],
        ["Infinity", 4],
        ["Maestro", 9],
        ["Cleave", 18],
        ["Infinity", 5],
        ["Infinity", 6],
        ["Infinity", 7],
        ["Infinity", 8],
        ["Infinity", 9],
        ["Infinity", 10],
        ["Cleave", 19],
        ["Legacy", 8],
        ["Legacy", 9],
        ["Legacy", 10],
        ["Legacy", 11],
        ["Legacy", 12],
        ["Legacy", 13],
        ["Cleave", 20],
        ["Cleave", 21],
        ["Cleave", 22],
        ["Cleave", 23],
        ["Cleave", 24],
        ["Cleave", 25],
        ["Cleave", 26],
        ["Cleave", 27],
        ["Cleave", 28],
        ["Legacy", 14],
        ["Legacy", 15],
        ["Legacy", 16],
        ["Cleave", 29],
        ["Maestro", 10],
        ["Maestro", 11],
        ["Maestro", 12],
        ["Maestro", 13],
        ["Maestro", 14],
        ["Storm", 2],
        ["Maestro", 15],
        ["Cleave", 30],
        ["Infinity", 11],
        ["Maestro", 16],
        ["Legacy", 17],
        ["Legacy", 18],
        ["Legacy", 19],
        ["Maestro", 17],
        ["Storm", 3],
        ["Infinity", 12],
        ["Maestro", 18],
        ["Storm", 4],
        ["Maestro", 19],
        ["Infinity", 13],
        ["Infinity", 14],
        ["Infinity", 15],
        ["Infinity", 16],
        ["Infinity", 17],
        ["Infinity", 18],
        ["Infinity", 19],
        ["Infinity", 20],
        ["Storm", 5],
        ["Storm", 6],
        ["Storm", 7],
        ["Storm", 8],
        ["Storm", 9],
        ["Storm", 10],
        ["Maestro", 20],
        ["Maestro", 21],
        ["Maestro", 22],
        ["Maestro", 23],
        ["Legacy", 20],
        ["Legacy", 21],
        ["Legacy", 22],
        ["Legacy", 23],
        ["Legacy", 24],
        ["Legacy", 25],
        ["Ruin", 2],
        ["Maestro", 24],
        ["Infinity", 21],
        ["Infinity", 22],
        ["Infinity", 23],
        ["Infinity", 24],
        ["Infinity", 25],
        ["Infinity", 26],
        ["Infinity", 27],
        ["Infinity", 28],
        ["Infinity", 29],
        ["Infinity", 30],
        ["Legacy", 26],
        ["Legacy", 27],
        ["Legacy", 28],
        ["Maestro", 25],
        ["Maestro", 26],
        ["Maestro", 27],
        ["Maestro", 28],
        ["Maestro", 29],
        ["Maestro", 30],
        ["Ruin", 3],
        ["Ruin", 4],
        ["Ruin", 5],
        ["Ruin", 6],
        ["Ruin", 7],
        ["Ruin", 8],
        ["Ruin", 9],
        ["Ruin", 10],
        ["Storm", 11],
        ["Storm", 12],
        ["Storm", 13],
        ["Storm", 14],
        ["Storm", 15],
        ["Storm", 16],
        ["Storm", 17],
        ["Storm", 18],
        ["Storm", 19],
        ["Storm", 20],
        ["Storm", 21],
        ["Storm", 22],
        ["Storm", 23],
        ["Storm", 24],
        ["Storm", 25],
        ["Storm", 26],
        ["Storm", 27],
        ["Storm", 28],
        ["Storm", 29],
        ["Storm", 30],
        ["Ruin", 11],
        ["Ruin", 12],
        ["Ruin", 13],
        ["Ruin", 14],
        ["Ruin", 15],
        ["Ruin", 16],
        ["Ruin", 17],
        ["Ruin", 18],
        ["Ruin", 19],
        ["Ruin", 20],
        ["Ruin", 21],
        ["Ruin", 22],
        ["Ruin", 23],
        ["Ruin", 24],
        ["Ruin", 25],
        ["Ruin", 26],
        ["Ruin", 27],
        ["Ruin", 28],
        ["Ruin", 29],
        ["Ruin", 30],
        ["Legacy", 29],
        ["Legacy", 30],
      ],
      Burst: [
        ["Cleave", 1],
        ["Infinity", 1],
        ["Cleave", 2],
        ["NOTE", "HEXA Stat: Main 0→2 (5 SE / 10 Frag unlock, 10 Frag/roll)"],
        ["Legacy", 1],
        ["Maestro", 2],
        ["Cleave", 3],
        ["Cleave", 4],
        ["Legacy", 2],
        ["Legacy", 3],
        ["Legacy", 4],
        [
          "NOTE",
          "HEXA Stat: continue until maxed (see HEXA Stats tab for cost)",
        ],
        ["Maestro", 3],
        ["Cleave", 5],
        ["Maestro", 4],
        ["Cleave", 6],
        ["Maestro", 5],
        ["Storm", 1],
        ["Cleave", 7],
        ["Legacy", 5],
        ["Legacy", 6],
        ["Legacy", 7],
        ["Infinity", 2],
        ["Maestro", 6],
        ["Cleave", 8],
        ["Maestro", 7],
        ["Cleave", 9],
        ["Infinity", 3],
        ["Maestro", 8],
        ["Infinity", 4],
        ["Maestro", 9],
        ["Infinity", 5],
        ["Infinity", 6],
        ["Infinity", 7],
        ["Infinity", 8],
        ["Infinity", 9],
        ["Infinity", 10],
        ["Ruin", 1],
        ["Legacy", 8],
        ["Legacy", 9],
        ["Legacy", 10],
        ["Legacy", 11],
        ["Legacy", 12],
        ["Legacy", 13],
        ["Cleave", 10],
        ["Cleave", 11],
        ["Cleave", 12],
        ["Cleave", 13],
        ["Cleave", 14],
        ["Cleave", 15],
        ["Legacy", 14],
        ["Legacy", 15],
        ["Legacy", 16],
        ["Cleave", 16],
        ["Maestro", 10],
        ["Maestro", 11],
        ["Maestro", 12],
        ["Maestro", 13],
        ["Maestro", 14],
        ["Cleave", 17],
        ["Maestro", 15],
        ["Legacy", 17],
        ["Legacy", 18],
        ["Legacy", 19],
        ["Cleave", 18],
        ["Infinity", 11],
        ["Maestro", 16],
        ["Cleave", 19],
        ["Maestro", 17],
        ["Infinity", 12],
        ["Maestro", 18],
        ["Storm", 2],
        ["Maestro", 19],
        ["Infinity", 13],
        ["Infinity", 14],
        ["Infinity", 15],
        ["Infinity", 16],
        ["Infinity", 17],
        ["Infinity", 18],
        ["Infinity", 19],
        ["Infinity", 20],
        ["Legacy", 20],
        ["Legacy", 21],
        ["Legacy", 22],
        ["Legacy", 23],
        ["Legacy", 24],
        ["Legacy", 25],
        ["Maestro", 20],
        ["Maestro", 21],
        ["Maestro", 22],
        ["Storm", 3],
        ["Maestro", 23],
        ["Legacy", 26],
        ["Legacy", 27],
        ["Legacy", 28],
        ["Cleave", 20],
        ["Cleave", 21],
        ["Cleave", 22],
        ["Cleave", 23],
        ["Cleave", 24],
        ["Cleave", 25],
        ["Cleave", 26],
        ["Maestro", 24],
        ["Cleave", 27],
        ["Storm", 4],
        ["Cleave", 28],
        ["Infinity", 21],
        ["Infinity", 22],
        ["Infinity", 23],
        ["Infinity", 24],
        ["Infinity", 25],
        ["Infinity", 26],
        ["Infinity", 27],
        ["Infinity", 28],
        ["Infinity", 29],
        ["Infinity", 30],
        ["Maestro", 25],
        ["Maestro", 26],
        ["Maestro", 27],
        ["Maestro", 28],
        ["Maestro", 29],
        ["Maestro", 30],
        ["Cleave", 29],
        ["Storm", 5],
        ["Storm", 6],
        ["Storm", 7],
        ["Storm", 8],
        ["Storm", 9],
        ["Storm", 10],
        ["Ruin", 2],
        ["Cleave", 30],
        ["Ruin", 3],
        ["Ruin", 4],
        ["Ruin", 5],
        ["Ruin", 6],
        ["Ruin", 7],
        ["Ruin", 8],
        ["Ruin", 9],
        ["Ruin", 10],
        ["Storm", 11],
        ["Storm", 12],
        ["Storm", 13],
        ["Storm", 14],
        ["Storm", 15],
        ["Storm", 16],
        ["Storm", 17],
        ["Storm", 18],
        ["Storm", 19],
        ["Storm", 20],
        ["Storm", 21],
        ["Storm", 22],
        ["Storm", 23],
        ["Storm", 24],
        ["Storm", 25],
        ["Storm", 26],
        ["Storm", 27],
        ["Storm", 28],
        ["Storm", 29],
        ["Storm", 30],
        ["Ruin", 11],
        ["Ruin", 12],
        ["Ruin", 13],
        ["Ruin", 14],
        ["Ruin", 15],
        ["Ruin", 16],
        ["Ruin", 17],
        ["Ruin", 18],
        ["Ruin", 19],
        ["Ruin", 20],
        ["Ruin", 21],
        ["Ruin", 22],
        ["Ruin", 23],
        ["Ruin", 24],
        ["Ruin", 25],
        ["Ruin", 26],
        ["Ruin", 27],
        ["Ruin", 28],
        ["Ruin", 29],
        ["Ruin", 30],
        ["Legacy", 29],
        ["Legacy", 30],
      ],
    },
  },

  Kanna: {
    nodes: [
      {
        key: "m1",
        name: "Mastery Core 1 (HEXA Soul-Shatter Talisman: Dance & HEXA Heart-Wreck Talisman)",
        type: "mastery",
        level: 0,
      },
      {
        key: "m2",
        name: "Mastery Core 2 (HEXA Summon Oni, HEXA [Order] Spinning Strike, & HEXA [Order] Pulverizing Strike)",
        type: "mastery",
        level: 0,
      },
      {
        key: "m3",
        name: "Mastery Core 3 (HEXA Summon Tengu & HEXA Shade-Fletched Arrow)",
        type: "mastery",
        level: 0,
      },
      {
        key: "m4",
        name: "Mastery Core 4 (HEXA Summon Orochi & HEXA [Order] Execute)",
        type: "mastery",
        level: 0,
      },
      { key: "sol hecate", name: "Sol Hecate", type: "common12", level: 0 },
      { key: "venom", name: "Venom", type: "enhancement", level: 0 },
      {
        key: "hakumenkonmou",
        name: "Hakumenkonmou",
        type: "enhancement",
        level: 0,
      },
      {
        key: "destruction",
        name: "Destruction",
        type: "enhancement",
        level: 0,
      },
      {
        key: "twilight bloom",
        name: "Twilight Bloom",
        type: "enhancement",
        level: 0,
      },
      {
        key: "radiant flame",
        name: "Radiant Flame",
        type: "enhancement",
        level: 0,
      },
      { key: "origin", name: "Origin", type: "skill12", level: 1 },
      { key: "ascent", name: "Ascent", type: "skill12", level: 0 },
    ],
    priorities: {
      Default: [
        ["m2", 1],
        ["m4", 1],
        ["m3", 1],
        ["m1", 1],
        ["m2", 2],
        ["sol hecate", 1],
        ["m2", 7],
        ["m4", 2],
        ["m2", 9],
        ["m3", 2],
        ["m4", 4],
        ["m3", 4],
        ["m4", 6],
        ["m3", 5],
        ["m4", 7],
        ["m3", 6],
        ["m4", 8],
        ["m2", 15],
        ["m3", 7],
        ["venom", 1],
        ["hakumenkonmou", 1],
        ["m4", 9],
        ["m2", 16],
        ["m3", 8],
        ["m1", 3],
        ["m2", 17],
        ["m3", 9],
        ["m2", 19],
        ["sol hecate", 2],
        ["destruction", 1],
        ["sol hecate", 3],
        ["m1", 6],
        ["sol hecate", 4],
        ["m2", 26],
        ["m4", 14],
        ["m2", 27],
        ["m4", 15],
        ["m2", 28],
        ["sol hecate", 5],
        ["origin", 2],
        ["m2", 29],
        ["m4", 16],
        ["m3", 15],
        ["sol hecate", 6],
        ["m4", 17],
        ["m1", 9],
        ["m3", 16],
        ["origin", 3],
        ["m4", 18],
        ["sol hecate", 7],
        ["m3", 17],
        ["m4", 19],
        ["sol hecate", 8],
        ["twilight bloom", 1],
        ["origin", 4],
        ["m3", 18],
        ["ascent", 1],
        ["m3", 19],
        ["sol hecate", 9],
        ["origin", 6],
        ["m4", 25],
        ["venom", 2],
        ["hakumenkonmou", 2],
        ["m4", 27],
        ["origin", 7],
        ["m4", 28],
        ["m3", 26],
        ["m4", 29],
        ["origin", 8],
        ["venom", 3],
        ["m2", 30],
        ["hakumenkonmou", 3],
        ["m3", 27],
        ["m1", 15],
        ["m3", 28],
        ["origin", 9],
        ["m3", 29],
        ["venom", 4],
        ["hakumenkonmou", 4],
        ["destruction", 2],
        ["venom", 10],
        ["hakumenkonmou", 10],
        ["ascent", 2],
        ["m1", 18],
        ["twilight bloom", 7],
        ["origin", 11],
        ["destruction", 3],
        ["ascent", 3],
        ["sol hecate", 15],
        ["origin", 12],
        ["destruction", 4],
        ["sol hecate", 16],
        ["origin", 13],
        ["ascent", 4],
        ["destruction", 10],
        ["sol hecate", 17],
        ["origin", 14],
        ["sol hecate", 18],
        ["ascent", 5],
        ["m1", 24],
        ["sol hecate", 19],
        ["origin", 15],
        ["m4", 30],
        ["m1", 27],
        ["ascent", 6],
        ["origin", 16],
        ["m3", 30],
        ["venom", 11],
        ["hakumenkonmou", 11],
        ["ascent", 7],
        ["origin", 18],
        ["ascent", 8],
        ["venom", 12],
        ["hakumenkonmou", 12],
        ["radiant flame", 10],
        ["origin", 30],
        ["radiant flame", 20],
        ["sol hecate", 30],
        ["ascent", 9],
        ["venom", 20],
        ["hakumenkonmou", 20],
        ["m1", 29],
        ["twilight bloom", 13],
        ["m1", 30],
        ["destruction", 11],
        ["venom", 30],
        ["hakumenkonmou", 30],
        ["destruction", 20],
        ["twilight bloom", 19],
        ["radiant flame", 30],
        ["ascent", 14],
        ["destruction", 30],
        ["ascent", 19],
        ["twilight bloom", 25],
        ["ascent", 30],
        ["twilight bloom", 30],
      ],
    },
  },

  "Demon Slayer": {
    nodes: [
      { key: "Demon Impact", type: "mastery", level: 0 },
      { key: "Demon Lash", type: "mastery", level: 0 },
      { key: "Dark Metamorphosis / Demon Cry", type: "mastery", level: 0 },
      { key: "Cerberus Chomp / Demonic Descent", type: "mastery", level: 0 },
      { key: "Nightmare", type: "skill12", level: 0 },
      { key: "Amethystine Incursion", type: "skill12", level: 0 },
      { key: "Wrath of Satan", type: "skill3", level: 0 },
      { key: "Demon Awakening", type: "enhancement", level: 0 },
      { key: "Spirit of Rage", type: "enhancement", level: 0 },
      { key: "Orthrus", type: "enhancement", level: 0 },
      { key: "Demon Bane", type: "enhancement", level: 0 },
      { key: "Sol Janus: Dawn / Twilight", type: "common12", level: 0 },
      {
        key: "Sol Hecate: Styx / Charon / Phlegethon",
        type: "common12",
        level: 0,
      },
      { key: "Common 4", type: "common12", level: 0 },
      { key: "Call Mastema", type: "common3", level: 0 },
    ],
    priorities: {
      // TODO (Sue): no step-by-step priority order was provided for this class yet.
      // Add one here in the same [key, targetLevel] format used for Kanna/Adele.
    },
  },

  // Add more classes here following the same pattern.
};
