PRIORITY_CONFIG["Bowmaster"] = {
  nodes: [
    { key: "Hurricane", name: "HEXA Hurricane", type: "mastery", level: 0 },
    { key: "Arrow Stream", name: "HEXA Arrow Stream / Arrow Blaster", type: "mastery", level: 0 },
    { key: "Quiver Cartridge", name: "HEXA Quiver Cartridge / Phoenix / [Extra Quiver Cartridge]", type: "mastery", level: 0 },
    { key: "Flash Mirage", name: "HEXA Flash Mirage / Gritty Gust", type: "mastery", level: 0 },
    { key: "Ascendant Shadow", type: "skill12", level: 1 },
    { key: "Flashpoint", type: "skill12", level: 0 },
    { key: "Storm of Arrows", type: "boost", level: 0 },
    { key: "Inhuman Speed", type: "boost", level: 0 },
    { key: "Quiver Barrage", type: "boost", level: 0 },
    { key: "Silhouette Mirage", type: "boost", level: 0 },
    { key: "Sol Janus", name: "Sol Janus: Dawn / Sol Janus: Twilight", type: "common12", level: 0 },
    { key: "Sol Hecate", name: "Sol Hecate: Styx / Charon / Phlegethon", type: "common12", level: 0 },
    { key: "Fury of the Wild", type: "common3", level: 0 },
  ],
  priorities: {
    All: [
      ["Hurricane", 1],
      ["Quiver Cartridge", 1],
      ["Flash Mirage", 1],
      ["Arrow Stream", 1],
      ["Sol Hecate", 1],
      ["Flashpoint", 1],
      ["Inhuman Speed", 1],
      ["Quiver Barrage", 1],
      ["Storm of Arrows", 1],
      ["Fury of the Wild", 1],
      ["Silhouette Mirage", 1],
      ["Hurricane", 2],
      ["Quiver Cartridge", 2],
      ["Flash Mirage", 2],
      ["Arrow Stream", 2],
      ["Hurricane", 3],
      ["Quiver Cartridge", 3],
      ["Flash Mirage", 3],
      ["Hurricane", 4],
      ["Quiver Cartridge", 4],
      ["Arrow Stream", 3],
      ["Flash Mirage", 4],
      ["Hurricane", 5],
      ["Quiver Cartridge", 5],
      ["Arrow Stream", 4],
      ["Flash Mirage", 5],
      ["Hurricane", 6],
      ["Quiver Cartridge", 6],
      ["Flash Mirage", 6],
      ["Arrow Stream", 5],
      ["Hurricane", 7],
      ["Quiver Cartridge", 7],
      ["Arrow Stream", 6],
      ["Flash Mirage", 7],
      ["Hurricane", 8],
      ["Quiver Cartridge", 8],
      ["Flash Mirage", 8],
      ["Arrow Stream", 7],
      ["Hurricane", 9],
      ["Quiver Cartridge", 9],
      ["Flash Mirage", 9],
      ["Arrow Stream", 8],
      ["Arrow Stream", 9],
      ["Sol Hecate", 2],
      ["Ascendant Shadow", 2],
      ["Sol Hecate", 3],
      ["Ascendant Shadow", 3],
      ["Fury of the Wild", 2],
      ["Inhuman Speed", 2],
      ["Sol Hecate", 4],
      ["Quiver Barrage", 2],
      ["Ascendant Shadow", 4],
      ["Inhuman Speed", 3],
      ["Fury of the Wild", 3],
      ["Sol Hecate", 5],
      ["Ascendant Shadow", 5],
      ["Quiver Barrage", 3],
      ["Storm of Arrows", 2],
      ["Inhuman Speed", 4],
      ["Sol Hecate", 6],
      ["Flashpoint", 2],
      ["Ascendant Shadow", 6],
      ["Fury of the Wild", 4],
      ["Quiver Barrage", 4],
      ["Sol Hecate", 7],
      ["Inhuman Speed", 5],
      ["Ascendant Shadow", 7],
      ["Storm of Arrows", 3],
      ["Sol Hecate", 8],
      ["Flashpoint", 3],
      ["Quiver Barrage", 5],
      ["Fury of the Wild", 5],
      ["Hurricane", 10],
      ["Hurricane", 11],
      ["Hurricane", 12],
      ["Hurricane", 13],
      ["Hurricane", 14],
      ["Hurricane", 15],
      ["Hurricane", 16],
      ["Hurricane", 17],
      ["Hurricane", 18],
      ["Hurricane", 19],
      ["Quiver Cartridge", 10],
      ["Quiver Cartridge", 11],
      ["Quiver Cartridge", 12],
      ["Quiver Cartridge", 13],
      ["Quiver Cartridge", 14],
      ["Quiver Cartridge", 15],
      ["Quiver Cartridge", 16],
      ["Quiver Cartridge", 17],
      ["Quiver Cartridge", 18],
      ["Quiver Cartridge", 19],
      ["Ascendant Shadow", 8],
      ["Inhuman Speed", 6],
      ["Flash Mirage", 10],
      ["Flash Mirage", 11],
      ["Flash Mirage", 12],
      ["Flash Mirage", 13],
      ["Flash Mirage", 14],
      ["Flash Mirage", 15],
      ["Flash Mirage", 16],
      ["Flash Mirage", 17],
      ["Flash Mirage", 18],
      ["Flash Mirage", 19],
      ["Storm of Arrows", 4],
      ["Sol Hecate", 9],
      ["Quiver Barrage", 6],
      ["Ascendant Shadow", 9],
      ["Fury of the Wild", 6],
      ["Flashpoint", 4],
      ["Inhuman Speed", 7],
      ["Arrow Stream", 10],
      ["Arrow Stream", 11],
      ["Arrow Stream", 12],
      ["Arrow Stream", 13],
      ["Arrow Stream", 14],
      ["Arrow Stream", 15],
      ["Arrow Stream", 16],
      ["Arrow Stream", 17],
      ["Arrow Stream", 18],
      ["Arrow Stream", 19],
      ["Storm of Arrows", 5],
      ["Quiver Barrage", 7],
      ["Inhuman Speed", 8],
      ["Fury of the Wild", 7],
      ["Flashpoint", 5],
      ["Quiver Barrage", 8],
      ["Inhuman Speed", 9],
      ["Inhuman Speed", 10],
      ["Storm of Arrows", 6],
      ["Fury of the Wild", 8],
      ["Flashpoint", 6],
      ["Quiver Barrage", 9],
      ["Quiver Barrage", 10],
      ["Silhouette Mirage", 2],
      ["Fury of the Wild", 9],
      ["Storm of Arrows", 7],
      ["Flashpoint", 7],
      ["Storm of Arrows", 8],
      ["Inhuman Speed", 11],
      ["Flashpoint", 8],
      ["Silhouette Mirage", 3],
      ["Hurricane", 20],
      ["Hurricane", 21],
      ["Hurricane", 22],
      ["Hurricane", 23],
      ["Hurricane", 24],
      ["Hurricane", 25],
      ["Hurricane", 26],
      ["Hurricane", 27],
      ["Hurricane", 28],
      ["Hurricane", 29],
      ["Storm of Arrows", 9],
      ["Storm of Arrows", 10],
      ["Quiver Barrage", 11],
      ["Quiver Cartridge", 20],
      ["Quiver Cartridge", 21],
      ["Quiver Cartridge", 22],
      ["Quiver Cartridge", 23],
      ["Quiver Cartridge", 24],
      ["Quiver Cartridge", 25],
      ["Quiver Cartridge", 26],
      ["Quiver Cartridge", 27],
      ["Quiver Cartridge", 28],
      ["Quiver Cartridge", 29],
      ["Flash Mirage", 20],
      ["Flash Mirage", 21],
      ["Flash Mirage", 22],
      ["Flash Mirage", 23],
      ["Flash Mirage", 24],
      ["Flash Mirage", 25],
      ["Flash Mirage", 26],
      ["Flash Mirage", 27],
      ["Flash Mirage", 28],
      ["Flash Mirage", 29],
      ["Flashpoint", 9],
      ["Inhuman Speed", 12],
      ["Silhouette Mirage", 4],
      ["Quiver Barrage", 12],
      ["Arrow Stream", 20],
      ["Arrow Stream", 21],
      ["Arrow Stream", 22],
      ["Arrow Stream", 23],
      ["Arrow Stream", 24],
      ["Arrow Stream", 25],
      ["Arrow Stream", 26],
      ["Arrow Stream", 27],
      ["Arrow Stream", 28],
      ["Arrow Stream", 29],
      ["Inhuman Speed", 13],
      ["Storm of Arrows", 11],
      ["Quiver Barrage", 13],
      ["Silhouette Mirage", 5],
      ["Inhuman Speed", 14],
      ["Storm of Arrows", 12],
      ["Quiver Barrage", 14],
      ["Silhouette Mirage", 6],
      ["Inhuman Speed", 15],
      ["Hurricane", 30],
      ["Quiver Cartridge", 30],
      ["Flash Mirage", 30],
      ["Quiver Barrage", 15],
      ["Storm of Arrows", 13],
      ["Inhuman Speed", 16],
      ["Silhouette Mirage", 7],
      ["Quiver Barrage", 16],
      ["Inhuman Speed", 17],
      ["Arrow Stream", 30],
      ["Silhouette Mirage", 8],
      ["Storm of Arrows", 14],
      ["Quiver Barrage", 17],
      ["Inhuman Speed", 18],
      ["Silhouette Mirage", 9],
      ["Silhouette Mirage", 10],
      ["Storm of Arrows", 15],
      ["Inhuman Speed", 19],
      ["Inhuman Speed", 20],
      ["Quiver Barrage", 18],
      ["Ascendant Shadow", 10],
      ["Ascendant Shadow", 11],
      ["Ascendant Shadow", 12],
      ["Ascendant Shadow", 13],
      ["Ascendant Shadow", 14],
      ["Ascendant Shadow", 15],
      ["Ascendant Shadow", 16],
      ["Ascendant Shadow", 17],
      ["Ascendant Shadow", 18],
      ["Ascendant Shadow", 19],
      ["Storm of Arrows", 16],
      ["Inhuman Speed", 21],
      ["Quiver Barrage", 19],
      ["Quiver Barrage", 20],
      ["Inhuman Speed", 22],
      ["Storm of Arrows", 17],
      ["Quiver Barrage", 21],
      ["Silhouette Mirage", 11],
      ["Inhuman Speed", 23],
      ["Sol Hecate", 10],
      ["Sol Hecate", 11],
      ["Sol Hecate", 12],
      ["Sol Hecate", 13],
      ["Sol Hecate", 14],
      ["Sol Hecate", 15],
      ["Sol Hecate", 16],
      ["Sol Hecate", 17],
      ["Sol Hecate", 18],
      ["Sol Hecate", 19],
      ["Quiver Barrage", 22],
      ["Storm of Arrows", 18],
      ["Inhuman Speed", 24],
      ["Quiver Barrage", 23],
      ["Storm of Arrows", 19],
      ["Storm of Arrows", 20],
      ["Inhuman Speed", 25],
      ["Quiver Barrage", 24],
      ["Silhouette Mirage", 12],
      ["Fury of the Wild", 10],
      ["Fury of the Wild", 11],
      ["Fury of the Wild", 12],
      ["Fury of the Wild", 13],
      ["Fury of the Wild", 14],
      ["Fury of the Wild", 15],
      ["Fury of the Wild", 16],
      ["Fury of the Wild", 17],
      ["Fury of the Wild", 18],
      ["Fury of the Wild", 19],
      ["Inhuman Speed", 26],
      ["Storm of Arrows", 21],
      ["Quiver Barrage", 25],
      ["Inhuman Speed", 27],
      ["Storm of Arrows", 22],
      ["Quiver Barrage", 26],
      ["Silhouette Mirage", 13],
      ["Inhuman Speed", 28],
      ["Quiver Barrage", 27],
      ["Storm of Arrows", 23],
      ["Inhuman Speed", 29],
      ["Inhuman Speed", 30],
      ["Quiver Barrage", 28],
      ["Storm of Arrows", 24],
      ["Silhouette Mirage", 14],
      ["Quiver Barrage", 29],
      ["Quiver Barrage", 30],
      ["Storm of Arrows", 25],
      ["Flashpoint", 10],
      ["Flashpoint", 11],
      ["Flashpoint", 12],
      ["Flashpoint", 13],
      ["Flashpoint", 14],
      ["Flashpoint", 15],
      ["Flashpoint", 16],
      ["Flashpoint", 17],
      ["Flashpoint", 18],
      ["Flashpoint", 19],
      ["Silhouette Mirage", 15],
      ["Storm of Arrows", 26],
      ["Ascendant Shadow", 20],
      ["Ascendant Shadow", 21],
      ["Ascendant Shadow", 22],
      ["Ascendant Shadow", 23],
      ["Ascendant Shadow", 24],
      ["Ascendant Shadow", 25],
      ["Ascendant Shadow", 26],
      ["Ascendant Shadow", 27],
      ["Ascendant Shadow", 28],
      ["Ascendant Shadow", 29],
      ["Storm of Arrows", 27],
      ["Silhouette Mirage", 16],
      ["Storm of Arrows", 28],
      ["Storm of Arrows", 29],
      ["Storm of Arrows", 30],
      ["Silhouette Mirage", 17],
      ["Sol Hecate", 20],
      ["Sol Hecate", 21],
      ["Sol Hecate", 22],
      ["Sol Hecate", 23],
      ["Sol Hecate", 24],
      ["Sol Hecate", 25],
      ["Sol Hecate", 26],
      ["Sol Hecate", 27],
      ["Sol Hecate", 28],
      ["Sol Hecate", 29],
      ["Silhouette Mirage", 18],
      ["Silhouette Mirage", 19],
      ["Silhouette Mirage", 20],
      ["Fury of the Wild", 20],
      ["Fury of the Wild", 21],
      ["Fury of the Wild", 22],
      ["Fury of the Wild", 23],
      ["Fury of the Wild", 24],
      ["Fury of the Wild", 25],
      ["Fury of the Wild", 26],
      ["Fury of the Wild", 27],
      ["Fury of the Wild", 28],
      ["Fury of the Wild", 29],
      ["Silhouette Mirage", 21],
      ["Ascendant Shadow", 30],
      ["Silhouette Mirage", 22],
      ["Silhouette Mirage", 23],
      ["Silhouette Mirage", 24],
      ["Sol Hecate", 30],
      ["Flashpoint", 20],
      ["Flashpoint", 21],
      ["Flashpoint", 22],
      ["Flashpoint", 23],
      ["Flashpoint", 24],
      ["Flashpoint", 25],
      ["Flashpoint", 26],
      ["Flashpoint", 27],
      ["Flashpoint", 28],
      ["Flashpoint", 29],
      ["Silhouette Mirage", 25],
      ["Silhouette Mirage", 26],
      ["Silhouette Mirage", 27],
      ["Fury of the Wild", 30],
      ["Silhouette Mirage", 28],
      ["Silhouette Mirage", 29],
      ["Silhouette Mirage", 30],
      ["Flashpoint", 30],
    ],
  },
};
