PRIORITY_CONFIG["Hero"] = {
  nodes: [
    { key: "Raging Blow", name: "HEXA Raging Blow", type: "mastery", level: 0 },
    { key: "Rising Rage", name: "HEXA Rising Rage", type: "mastery", level: 0 },
    { key: "Beam Blade", name: "HEXA Beam Blade / [Furious Edge]", type: "mastery", level: 0 },
    { key: "Puncture", name: "HEXA Puncture / Final Attack / Valhalla", type: "mastery", level: 0 },
    { key: "Soul Calibur", name: "Soul Calibur", type: "skill12", level: 1 },
    { key: "Ultrasonic Slash", name: "Ultrasonic Slash", type: "skill12", level: 0 },
    { key: "Burning Soul Blade", name: "Burning Soul Blade", type: "boost", level: 0 },
    { key: "Instinctual Combo", name: "Instinctual Combo", type: "boost", level: 0 },
    { key: "Worldreaver", name: "Worldreaver", type: "boost", level: 0 },
    { key: "Sword Illusion", name: "Sword Illusion", type: "boost", level: 0 },
    { key: "Sol Janus", name: "Sol Janus: Dawn / Sol Janus: Twilight", type: "common12", level: 0 },
    { key: "Sol Hecate", name: "Sol Hecate: Styx / Charon / Phlegethon", type: "common12", level: 0 },
    { key: "Blitz Shield", name: "Blitz Shield / Blitz Burst", type: "common3", level: 0 },
  ],
  priorities: {
    All: [
      ["Beam Blade", 1],
      ["Rising Rage", 1],
      ["Rising Rage", 2],
      ["Puncture", 1],
      ["Puncture", 2],
      ["Raging Blow", 1],
      ["Raging Blow", 2],
      ["Raging Blow", 3],
      ["Raging Blow", 4],
      ["Raging Blow", 5],
      ["Raging Blow", 6],
      ["Raging Blow", 7],
      ["Raging Blow", 8],
      ["Raging Blow", 9],
      ["Sol Hecate", 1],
      ["Rising Rage", 3],
      ["Rising Rage", 4],
      ["Rising Rage", 5],
      ["Instinctual Combo", 1],
      ["Puncture", 3],
      ["Puncture", 4],
      ["Puncture", 5],
      ["Rising Rage", 6],
      ["Rising Rage", 7],
      ["Rising Rage", 8],
      ["Rising Rage", 9],
      ["Burning Soul Blade", 1],
      ["Beam Blade", 2],
      ["Beam Blade", 3],
      ["Raging Blow", 10],
      ["Raging Blow", 11],
      ["Raging Blow", 12],
      ["Raging Blow", 13],
      ["Raging Blow", 14],
      ["Raging Blow", 15],
      ["Raging Blow", 16],
      ["Raging Blow", 17],
      ["Raging Blow", 18],
      ["Puncture", 6],
      ["Puncture", 7],
      ["Puncture", 8],
      ["Puncture", 9],
      ["Beam Blade", 4],
      ["Beam Blade", 5],
      ["Beam Blade", 6],
      ["Blitz Shield", 1],
      ["NOTE", "HEXA Stat I"],
      ["Raging Blow", 19],
      ["Raging Blow", 20],
      ["Raging Blow", 21],
      ["Raging Blow", 22],
      ["Raging Blow", 23],
      ["Raging Blow", 24],
      ["Raging Blow", 25],
      ["Raging Blow", 26],
      ["Raging Blow", 27],
      ["Raging Blow", 28],
      ["Raging Blow", 29],
      ["Beam Blade", 7],
      ["Beam Blade", 8],
      ["Beam Blade", 9],
      ["Rising Rage", 10],
      ["Rising Rage", 11],
      ["Rising Rage", 12],
      ["Rising Rage", 13],
      ["Rising Rage", 14],
      ["Rising Rage", 15],
      ["Rising Rage", 16],
      ["Rising Rage", 17],
      ["Rising Rage", 18],
      ["Sword Illusion", 1],
      ["Instinctual Combo", 2],
      ["Instinctual Combo", 3],
      ["Instinctual Combo", 4],
      ["Soul Calibur", 2],
      ["Soul Calibur", 3],
      ["Blitz Shield", 2],
      ["Blitz Shield", 3],
      ["Sol Hecate", 2],
      ["Sol Hecate", 3],
      ["Sol Hecate", 4],
      ["Ultrasonic Slash", 1],
      ["Ultrasonic Slash", 2],
      ["Ultrasonic Slash", 3],
      ["Puncture", 10],
      ["Puncture", 11],
      ["Puncture", 12],
      ["Puncture", 13],
      ["Puncture", 14],
      ["Puncture", 15],
      ["Puncture", 16],
      ["Puncture", 17],
      ["Puncture", 18],
      ["Rising Rage", 19],
      ["Rising Rage", 20],
      ["Rising Rage", 21],
      ["Rising Rage", 22],
      ["Rising Rage", 23],
      ["Rising Rage", 24],
      ["Rising Rage", 25],
      ["Rising Rage", 26],
      ["Rising Rage", 27],
      ["NOTE", "HEXA Stat II"],
      ["Instinctual Combo", 5],
      ["Instinctual Combo", 6],
      ["Instinctual Combo", 7],
      ["Instinctual Combo", 8],
      ["Instinctual Combo", 9],
      ["Instinctual Combo", 10],
      ["Burning Soul Blade", 2],
      ["Burning Soul Blade", 3],
      ["Blitz Shield", 4],
      ["Blitz Shield", 5],
      ["Soul Calibur", 4],
      ["Soul Calibur", 5],
      ["Soul Calibur", 6],
      ["Sol Hecate", 5],
      ["Sol Hecate", 6],
      ["Sol Hecate", 7],
      ["Ultrasonic Slash", 4],
      ["Ultrasonic Slash", 5],
      ["Ultrasonic Slash", 6],
      ["Puncture", 19],
      ["Puncture", 20],
      ["Puncture", 21],
      ["Puncture", 22],
      ["Puncture", 23],
      ["Puncture", 24],
      ["Puncture", 25],
      ["Puncture", 26],
      ["Beam Blade", 10],
      ["Beam Blade", 11],
      ["Beam Blade", 12],
      ["Beam Blade", 13],
      ["Beam Blade", 14],
      ["Beam Blade", 15],
      ["Beam Blade", 16],
      ["Beam Blade", 17],
      ["Rising Rage", 28],
      ["Rising Rage", 29],
      ["Burning Soul Blade", 4],
      ["Burning Soul Blade", 5],
      ["Burning Soul Blade", 6],
      ["Burning Soul Blade", 7],
      ["Burning Soul Blade", 8],
      ["Burning Soul Blade", 9],
      ["Burning Soul Blade", 10],
      ["Blitz Shield", 6],
      ["Blitz Shield", 7],
      ["Blitz Shield", 8],
      ["Blitz Shield", 9],
      ["Raging Blow", 30],
      ["Soul Calibur", 7],
      ["Soul Calibur", 8],
      ["Soul Calibur", 9],
      ["Sol Hecate", 8],
      ["Sol Hecate", 9],
      ["Ultrasonic Slash", 7],
      ["Ultrasonic Slash", 8],
      ["Ultrasonic Slash", 9],
      ["Puncture", 27],
      ["Puncture", 28],
      ["Puncture", 29],
      ["Beam Blade", 18],
      ["Beam Blade", 19],
      ["Instinctual Combo", 11],
      ["Instinctual Combo", 12],
      ["Instinctual Combo", 13],
      ["Instinctual Combo", 14],
      ["Instinctual Combo", 15],
      ["Instinctual Combo", 16],
      ["Instinctual Combo", 17],
      ["Instinctual Combo", 18],
      ["Instinctual Combo", 19],
      ["Instinctual Combo", 20],
      ["Sword Illusion", 2],
      ["Sword Illusion", 3],
      ["Beam Blade", 20],
      ["Beam Blade", 21],
      ["Beam Blade", 22],
      ["Beam Blade", 23],
      ["Beam Blade", 24],
      ["Beam Blade", 25],
      ["Beam Blade", 26],
      ["Beam Blade", 27],
      ["Beam Blade", 28],
      ["Beam Blade", 29],
      ["Sol Hecate", 10],
      ["Sol Hecate", 11],
      ["Sol Hecate", 12],
      ["Sol Hecate", 13],
      ["Sol Hecate", 14],
      ["Sol Hecate", 15],
      ["Blitz Shield", 10],
      ["Blitz Shield", 11],
      ["Blitz Shield", 12],
      ["Blitz Shield", 13],
      ["Blitz Shield", 14],
      ["Burning Soul Blade", 11],
      ["Burning Soul Blade", 12],
      ["Burning Soul Blade", 13],
      ["Burning Soul Blade", 14],
      ["Burning Soul Blade", 15],
      ["Burning Soul Blade", 16],
      ["Burning Soul Blade", 17],
      ["Burning Soul Blade", 18],
      ["Burning Soul Blade", 19],
      ["Burning Soul Blade", 20],
      ["NOTE", "HEXA Stat III"],
      ["Rising Rage", 30],
      ["Soul Calibur", 10],
      ["Soul Calibur", 11],
      ["Soul Calibur", 12],
      ["Soul Calibur", 13],
      ["Soul Calibur", 14],
      ["Soul Calibur", 15],
      ["Soul Calibur", 16],
      ["Soul Calibur", 17],
      ["Ultrasonic Slash", 10],
      ["Ultrasonic Slash", 11],
      ["Ultrasonic Slash", 12],
      ["Ultrasonic Slash", 13],
      ["Ultrasonic Slash", 14],
      ["Ultrasonic Slash", 15],
      ["Ultrasonic Slash", 16],
      ["Ultrasonic Slash", 17],
      ["Sword Illusion", 4],
      ["Sword Illusion", 5],
      ["Sword Illusion", 6],
      ["Sword Illusion", 7],
      ["Sword Illusion", 8],
      ["Sword Illusion", 9],
      ["Sword Illusion", 10],
      ["Puncture", 30],
      ["Sol Hecate", 16],
      ["Sol Hecate", 17],
      ["Sol Hecate", 18],
      ["Sol Hecate", 19],
      ["Soul Calibur", 18],
      ["Soul Calibur", 19],
      ["Ultrasonic Slash", 18],
      ["Ultrasonic Slash", 19],
      ["Sol Hecate", 20],
      ["Sol Hecate", 21],
      ["Sol Hecate", 22],
      ["Sol Hecate", 23],
      ["Sol Hecate", 24],
      ["Sol Hecate", 25],
      ["Sol Hecate", 26],
      ["Sol Hecate", 27],
      ["Sol Hecate", 28],
      ["Sol Hecate", 29],
      ["Sol Hecate", 30],
      ["Instinctual Combo", 21],
      ["Instinctual Combo", 22],
      ["Instinctual Combo", 23],
      ["Instinctual Combo", 24],
      ["Instinctual Combo", 25],
      ["Instinctual Combo", 26],
      ["Instinctual Combo", 27],
      ["Instinctual Combo", 28],
      ["Instinctual Combo", 29],
      ["Beam Blade", 30],
      ["Soul Calibur", 20],
      ["Soul Calibur", 21],
      ["Soul Calibur", 22],
      ["Soul Calibur", 23],
      ["Soul Calibur", 24],
      ["Soul Calibur", 25],
      ["Soul Calibur", 26],
      ["Soul Calibur", 27],
      ["Soul Calibur", 28],
      ["Soul Calibur", 29],
      ["Ultrasonic Slash", 20],
      ["Ultrasonic Slash", 21],
      ["Ultrasonic Slash", 22],
      ["Ultrasonic Slash", 23],
      ["Ultrasonic Slash", 24],
      ["Ultrasonic Slash", 25],
      ["Ultrasonic Slash", 26],
      ["Ultrasonic Slash", 27],
      ["Ultrasonic Slash", 28],
      ["Ultrasonic Slash", 29],
      ["Burning Soul Blade", 21],
      ["Burning Soul Blade", 22],
      ["Burning Soul Blade", 23],
      ["Burning Soul Blade", 24],
      ["Burning Soul Blade", 25],
      ["Burning Soul Blade", 26],
      ["Sword Illusion", 11],
      ["Sword Illusion", 12],
      ["Sword Illusion", 13],
      ["Sword Illusion", 14],
      ["Sword Illusion", 15],
      ["Sword Illusion", 16],
      ["Sword Illusion", 17],
      ["Sword Illusion", 18],
      ["Sword Illusion", 19],
      ["Sword Illusion", 20],
      ["Burning Soul Blade", 27],
      ["Burning Soul Blade", 28],
      ["Burning Soul Blade", 29],
      ["Instinctual Combo", 30],
      ["Blitz Shield", 15],
      ["Blitz Shield", 16],
      ["Blitz Shield", 17],
      ["Blitz Shield", 18],
      ["Blitz Shield", 19],
      ["Sword Illusion", 21],
      ["Sword Illusion", 22],
      ["Sword Illusion", 23],
      ["Sword Illusion", 24],
      ["Sword Illusion", 25],
      ["Soul Calibur", 30],
      ["Ultrasonic Slash", 30],
      ["Blitz Shield", 20],
      ["Blitz Shield", 21],
      ["Blitz Shield", 22],
      ["Blitz Shield", 23],
      ["Blitz Shield", 24],
      ["Blitz Shield", 25],
      ["Blitz Shield", 26],
      ["Blitz Shield", 27],
      ["Blitz Shield", 28],
      ["Blitz Shield", 29],
      ["Sword Illusion", 26],
      ["Sword Illusion", 27],
      ["Sword Illusion", 28],
      ["Sword Illusion", 29],
      ["Burning Soul Blade", 30],
      ["Sword Illusion", 30],
      ["Blitz Shield", 30],
      ["Worldreaver", 1],
      ["Worldreaver", 2],
      ["Worldreaver", 3],
      ["Worldreaver", 4],
      ["Worldreaver", 5],
      ["Worldreaver", 6],
      ["Worldreaver", 7],
      ["Worldreaver", 8],
      ["Worldreaver", 9],
      ["Worldreaver", 10],
      ["Worldreaver", 11],
      ["Worldreaver", 12],
      ["Worldreaver", 13],
      ["Worldreaver", 14],
      ["Worldreaver", 15],
      ["Worldreaver", 16],
      ["Worldreaver", 17],
      ["Worldreaver", 18],
      ["Worldreaver", 19],
      ["Worldreaver", 20],
      ["Worldreaver", 21],
      ["Worldreaver", 22],
      ["Worldreaver", 23],
      ["Worldreaver", 24],
      ["Worldreaver", 25],
      ["Worldreaver", 26],
      ["Worldreaver", 27],
      ["Worldreaver", 28],
      ["Worldreaver", 29],
      ["Worldreaver", 30],
    ],
  },
};
