PRIORITY_CONFIG["Hoyoung"] = {
  nodes: [
    {
      key: "apotheosis",
      name: "Sage: Apotheosis",
      type: "skill12",
      level: 1,
    },
    {
      key: "ascent",
      name: "Millenium Spirit",
      type: "skill12",
      level: 0,
    },
    {
      key: "rampage",
      name: "Sage: Clone Rampage",
      type: "boost",
      level: 0,
    },
    {
      key: "tiger",
      name: "Scroll: Tiger of Songyu",
      type: "boost",
      level: 0,
    },
    {
      key: "wrath of gods",
      name: "Sage: Wrath of Gods",
      type: "boost",
      level: 0,
    },
    {
      key: "apparition",
      name: "Sage: Three Paths Apparition",
      type: "boost",
      level: 0,
    },
    {
      key: "scroll",
      name: "HEXA Scroll: Star Vortex / Scroll: Butterfly Dream",
      type: "mastery",
      level: 0,
    },
    {
      key: "talisman",
      name: "HEXA Talisman: Clone / Talisman: Seeking Ghost Flame",
      type: "mastery",
      level: 0,
    },
    { key: "basics", name: "HEXA Heaven: Consuming Flames / Earth: Stone Tremor / Humanity: Gold-Banded Cudgel / [Universal Harmony]", type: "mastery", level: 0 },
    { key: "harmony", name: "HEXA Heaven: Iron Fan Gale / Earth: Ground-Shattering Wave / Humanity: As-You-Will Fan", type: "mastery", level: 0 },
    { key: "lotus", name: "Sol Janus: Dawn / Sol Janus: Twilight", type: "common12", level: 0 },
    { key: "hecate", name: "Sol Hecate: Styx / Charon / Phlegethon", type: "common12", level: 0 },
    { key: "lotus flower", name: "Lotus Flower", type: "common3", level: 0 },
  ],
  priorities: {
    All: [
      ["harmony", 1],
      ["talisman", 1],
      ["scroll", 1],
      ["hecate", 1],
      ["harmony", 2],
      ["harmony", 3],
      ["harmony", 4],
      ["harmony", 5],
      ["harmony", 6],
      ["scroll", 2],
      ["talisman", 2],
      ["scroll", 3],
      ["NOTE", "HEXA Stat I: level to 20"],
      ["scroll", 4],
      ["talisman", 3],
      ["talisman", 4],
      ["scroll", 5],
      ["scroll", 6],
      ["talisman", 5],
      ["scroll", 7],
      ["NOTE", "HEXA Stat II: level to 20"],
      ["talisman", 6],
      ["basics", 1],
      ["basics", 2],
      ["basics", 3],
      ["basics", 4],
      ["basics", 5],
      ["basics", 6],
      ["scroll", 8],
      ["harmony", 7],
      ["harmony", 8],
      ["harmony", 9],
      ["harmony", 10],
      ["harmony", 11],
      ["harmony", 12],
      ["talisman", 7],
      ["scroll", 9],
      ["basics", 7],
      ["talisman", 8],
      ["NOTE", "HEXA Stat III: level to 20"],
      ["basics", 8],
      ["wrath of gods", 1],
      ["talisman", 9],
      ["basics", 9],
      ["apparition", 1],
      ["rampage", 1],
      ["rampage", 2],
      ["rampage", 3],
      ["rampage", 4],
      ["rampage", 5],
      ["rampage", 6],
      ["harmony", 13],
      ["harmony", 14],
      ["harmony", 15],
      ["harmony", 16],
      ["harmony", 17],
      ["harmony", 18],
      ["rampage", 7],
      ["rampage", 8],
      ["lotus", 1],
      ["ascent", 1],
      ["rampage", 9],
      ["tiger", 1],
      ["scroll", 10],
      ["scroll", 11],
      ["scroll", 12],
      ["scroll", 13],
      ["scroll", 14],
      ["scroll", 15],
      ["lotus", 2],
      ["hecate", 2],
      ["scroll", 16],
      ["talisman", 10],
      ["talisman", 11],
      ["talisman", 12],
      ["talisman", 13],
      ["talisman", 14],
      ["apotheosis", 2],
      ["harmony", 19],
      ["harmony", 20],
      ["harmony", 21],
      ["harmony", 22],
      ["harmony", 23],
      ["harmony", 24],
      ["talisman", 15],
      ["basics", 10],
      ["basics", 11],
      ["basics", 12],
      ["basics", 13],
      ["basics", 14],
      ["scroll", 17],
      ["hecate", 3],
      ["basics", 15],
      ["lotus", 3],
      ["talisman", 16],
      ["scroll", 18],
      ["basics", 16],
      ["apotheosis", 3],
      ["talisman", 17],
      ["scroll", 19],
      ["hecate", 4],
      ["basics", 17],
      ["lotus", 4],
      ["talisman", 18],
      ["harmony", 25],
      ["harmony", 26],
      ["harmony", 27],
      ["harmony", 28],
      ["harmony", 29],
      ["harmony", 30],
      ["basics", 18],
      ["apotheosis", 4],
      ["ascent", 2],
      ["talisman", 19],
      ["hecate", 5],
      ["rampage", 10],
      ["rampage", 11],
      ["rampage", 12],
      ["rampage", 13],
      ["rampage", 14],
      ["basics", 19],
      ["lotus", 5],
      ["rampage", 15],
      ["apotheosis", 5],
      ["hecate", 6],
      ["ascent", 3],
      ["rampage", 16],
      ["lotus", 6],
      ["scroll", 20],
      ["scroll", 21],
      ["scroll", 22],
      ["scroll", 23],
      ["scroll", 24],
      ["scroll", 25],
      ["scroll", 26],
      ["hecate", 7],
      ["apotheosis", 6],
      ["rampage", 17],
      ["scroll", 27],
      ["lotus", 7],
      ["ascent", 4],
      ["hecate", 8],
      ["rampage", 18],
      ["scroll", 28],
      ["scroll", 29],
      ["wrath of gods", 2],
      ["talisman", 20],
      ["talisman", 21],
      ["talisman", 22],
      ["talisman", 23],
      ["talisman", 24],
      ["talisman", 25],
      ["apotheosis", 7],
      ["talisman", 26],
      ["basics", 20],
      ["basics", 21],
      ["basics", 22],
      ["basics", 23],
      ["basics", 24],
      ["basics", 25],
      ["rampage", 19],
      ["talisman", 27],
      ["basics", 26],
      ["lotus", 8],
      ["hecate", 9],
      ["apparition", 2],
      ["apotheosis", 8],
      ["ascent", 5],
      ["basics", 27],
      ["talisman", 28],
      ["talisman", 29],
      ["wrath of gods", 3],
      ["lotus", 9],
      ["apotheosis", 9],
      ["basics", 28],
      ["basics", 29],
      ["ascent", 6],
      ["apparition", 3],
      ["wrath of gods", 4],
      ["ascent", 7],
      ["wrath of gods", 5],
      ["wrath of gods", 6],
      ["wrath of gods", 7],
      ["wrath of gods", 8],
      ["wrath of gods", 9],
      ["wrath of gods", 10],
      ["apparition", 4],
      ["rampage", 20],
      ["rampage", 21],
      ["rampage", 22],
      ["rampage", 23],
      ["rampage", 24],
      ["rampage", 25],
      ["rampage", 26],
      ["ascent", 8],
      ["rampage", 27],
      ["apparition", 5],
      ["apparition", 6],
      ["apparition", 7],
      ["apparition", 8],
      ["apparition", 9],
      ["apparition", 10],
      ["tiger", 2],
      ["rampage", 28],
      ["ascent", 9],
      ["rampage", 29],
      ["tiger", 3],
      ["apotheosis", 10],
      ["apotheosis", 11],
      ["apotheosis", 12],
      ["apotheosis", 13],
      ["hecate", 10],
      ["hecate", 11],
      ["hecate", 12],
      ["hecate", 13],
      ["hecate", 14],
      ["hecate", 15],
      ["apotheosis", 14],
      ["scroll", 30],
      ["lotus", 10],
      ["lotus", 11],
      ["lotus", 12],
      ["lotus", 13],
      ["lotus", 14],
      ["tiger", 4],
      ["lotus", 15],
      ["apotheosis", 15],
      ["tiger", 5],
      ["tiger", 6],
      ["tiger", 7],
      ["tiger", 8],
      ["tiger", 9],
      ["tiger", 10],
      ["lotus", 16],
      ["hecate", 16],
      ["talisman", 30],
      ["apotheosis", 16],
      ["lotus", 17],
      ["basics", 30],
      ["hecate", 17],
      ["apotheosis", 17],
      ["lotus", 18],
      ["wrath of gods", 11],
      ["ascent", 10],
      ["ascent", 11],
      ["ascent", 12],
      ["ascent", 13],
      ["ascent", 14],
      ["hecate", 18],
      ["apotheosis", 18],
      ["lotus", 19],
      ["hecate", 19],
      ["hecate", 20],
      ["hecate", 21],
      ["hecate", 22],
      ["hecate", 23],
      ["hecate", 24],
      ["hecate", 25],
      ["hecate", 26],
      ["hecate", 27],
      ["hecate", 28],
      ["hecate", 29],
      ["hecate", 30],
      ["apparition", 11],
      ["apotheosis", 19],
      ["apotheosis", 20],
      ["ascent", 15],
      ["wrath of gods", 12],
      ["apotheosis", 21],
      ["ascent", 16],
      ["wrath of gods", 13],
      ["wrath of gods", 14],
      ["wrath of gods", 15],
      ["wrath of gods", 16],
      ["wrath of gods", 17],
      ["wrath of gods", 18],
      ["wrath of gods", 19],
      ["wrath of gods", 20],
      ["apotheosis", 22],
      ["apparition", 12],
      ["rampage", 30],
      ["apotheosis", 23],
      ["apotheosis", 24],
      ["apotheosis", 25],
      ["apotheosis", 26],
      ["apotheosis", 27],
      ["apotheosis", 28],
      ["apotheosis", 29],
      ["apotheosis", 30],
      ["ascent", 17],
      ["apparition", 13],
      ["apparition", 14],
      ["apparition", 15],
      ["apparition", 16],
      ["apparition", 17],
      ["apparition", 18],
      ["apparition", 19],
      ["apparition", 20],
      ["ascent", 18],
      ["lotus", 20],
      ["lotus", 21],
      ["lotus", 22],
      ["lotus", 23],
      ["lotus", 24],
      ["lotus", 25],
      ["ascent", 19],
      ["lotus", 26],
      ["wrath of gods", 21],
      ["wrath of gods", 22],
      ["wrath of gods", 23],
      ["wrath of gods", 24],
      ["wrath of gods", 25],
      ["wrath of gods", 26],
      ["wrath of gods", 27],
      ["wrath of gods", 28],
      ["wrath of gods", 29],
      ["wrath of gods", 30],
      ["lotus", 27],
      ["tiger", 11],
      ["apparition", 21],
      ["apparition", 22],
      ["apparition", 23],
      ["apparition", 24],
      ["apparition", 25],
      ["apparition", 26],
      ["apparition", 27],
      ["apparition", 28],
      ["apparition", 29],
      ["apparition", 30],
      ["lotus", 28],
      ["lotus", 29],
      ["tiger", 12],
      ["ascent", 20],
      ["ascent", 21],
      ["ascent", 22],
      ["ascent", 23],
      ["ascent", 24],
      ["ascent", 25],
      ["tiger", 13],
      ["tiger", 14],
      ["tiger", 15],
      ["tiger", 16],
      ["tiger", 17],
      ["tiger", 18],
      ["tiger", 19],
      ["tiger", 20],
      ["ascent", 26],
      ["ascent", 27],
      ["ascent", 28],
      ["ascent", 29],
      ["tiger", 21],
      ["tiger", 22],
      ["tiger", 23],
      ["tiger", 24],
      ["tiger", 25],
      ["tiger", 26],
      ["tiger", 27],
      ["tiger", 28],
      ["tiger", 29],
      ["tiger", 30],
      ["ascent", 30],
      ["lotus", 30],
    ],
  },
};
