PRIORITY_CONFIG["Kanna"] = {
  nodes: [
    {
      key: "m1",
      name: "Soul-Shatter Talisman: Dance & Heart-Wreck Talisman",
      type: "mastery",
      level: 0,
    },
    {
      key: "m2",
      name: "Summon Oni, [Order] Spinning Strike, & [Order] Pulverizing Strike",
      type: "mastery",
      level: 0,
    },
    {
      key: "m3",
      name: "Summon Tengu & Shade-Fletched Arrow",
      type: "mastery",
      level: 0,
    },
    {
      key: "m4",
      name: "Summon Orochi & [Order] Execute",
      type: "mastery",
      level: 0,
    },
    { key: "common1", name: "Sol Janus", type: "common12", level: 0 },
    { key: "common2", name: "Sol Hecate", type: "common12", level: 0 },
    { key: "common3", name: "Twilight Bloom", type: "common3", level: 0 },
    { key: "boost1", name: "Venom", type: "boost", level: 0 },
    { key: "boost2", name: "Hakumenkonmou", type: "boost", level: 0 },
    { key: "boost3", name: "Destruction", type: "boost", level: 0 },
    { key: "boost4", name: "Radiant Flame", type: "boost", level: 0 },
    {
      key: "origin",
      name: "[Divine Will] Advent of Crimson",
      type: "skill12",
      level: 0,
    },
    {
      key: "ascent",
      name: "[Divine Will] Final Rest",
      type: "skill12",
      level: 0,
    },
  ],
  priorities: {
    Default: [
      ["m2", 1],
      ["m4", 1],
      ["m3", 1],
      ["m1", 1],
      ["m2", 2],
      ["common2", 1],
      ["m2", 7],
      ["m4", 2],
      ["m2", 9],
      ["m3", 2],
      ["m4", 4],
      ["m3", 4],
      ["m4", 6],
      ["m3", 5],
      ["m4", 7],
      ["m3", 6],
      ["m4", 8],
      ["m2", 15],
      ["m3", 7],
      ["boost1", 1],
      ["boost2", 1],
      ["m4", 9],
      ["m2", 16],
      ["m3", 8],
      ["m1", 3],
      ["m2", 17],
      ["m3", 9],
      ["m2", 19],
      ["common2", 2],
      ["boost3", 1],
      ["common2", 3],
      ["m1", 6],
      ["common2", 4],
      ["m2", 26],
      ["m4", 14],
      ["m2", 27],
      ["m4", 15],
      ["m2", 28],
      ["common2", 5],
      ["origin", 2],
      ["m2", 29],
      ["m4", 16],
      ["m3", 15],
      ["common2", 6],
      ["m4", 17],
      ["m1", 9],
      ["m3", 16],
      ["origin", 3],
      ["m4", 18],
      ["common2", 7],
      ["m3", 17],
      ["m4", 19],
      ["common2", 8],
      ["common3", 1],
      ["origin", 4],
      ["m3", 18],
      ["ascent", 1],
      ["m3", 19],
      ["common2", 9],
      ["origin", 6],
      ["m4", 25],
      ["boost1", 2],
      ["boost2", 2],
      ["m4", 27],
      ["origin", 7],
      ["m4", 28],
      ["m3", 26],
      ["m4", 29],
      ["origin", 8],
      ["boost1", 3],
      ["m2", 30],
      ["boost2", 3],
      ["m3", 27],
      ["m1", 15],
      ["m3", 28],
      ["origin", 9],
      ["m3", 29],
      ["boost1", 4],
      ["boost2", 4],
      ["boost3", 2],
      ["boost1", 10],
      ["boost2", 10],
      ["ascent", 2],
      ["m1", 18],
      ["common3", 7],
      ["origin", 11],
      ["boost3", 3],
      ["ascent", 3],
      ["common2", 15],
      ["origin", 12],
      ["boost3", 4],
      ["common2", 16],
      ["origin", 13],
      ["ascent", 4],
      ["boost3", 10],
      ["common2", 17],
      ["origin", 14],
      ["common2", 18],
      ["ascent", 5],
      ["m1", 24],
      ["common2", 19],
      ["origin", 15],
      ["m4", 30],
      ["m1", 27],
      ["ascent", 6],
      ["origin", 16],
      ["m3", 30],
      ["boost1", 11],
      ["boost2", 11],
      ["ascent", 7],
      ["origin", 18],
      ["ascent", 8],
      ["boost1", 12],
      ["boost2", 12],
      ["boost4", 10],
      ["origin", 30],
      ["boost4", 20],
      ["common2", 30],
      ["ascent", 9],
      ["boost1", 20],
      ["boost2", 20],
      ["m1", 29],
      ["common3", 13],
      ["m1", 30],
      ["boost3", 11],
      ["boost1", 30],
      ["boost2", 30],
      ["boost3", 20],
      ["common3", 19],
      ["boost4", 30],
      ["ascent", 14],
      ["boost3", 30],
      ["ascent", 19],
      ["common3", 25],
      ["ascent", 30],
      ["common3", 30],
      [
        "NOTE",
        "Sol Janus was not part of the original priority source data — appended here per your instruction to level at lowest priority.",
      ],
      ["common1", 30],
    ],
  },
};
